### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by cr0hn**
Fix: the last version of aiohttp has some incompatibilities with version 1.x and the default version that pip install are 2.x and it raises an exception.

### CODE REVIEW

**Comment by smurfix** [comment]
Umm … why would you want to do that?

I just uploaded a version that adds compatibility with aiohttp 2.x (and etcd 3.1), at least to the extent that the initial tests pass.
If that's not sufficient, please submit a Python backtrace and/or a test case.

**Comment by cr0hn** [comment]
If you do:

```bash
pip install aio_etcd
```

And then try to run this code:

```python

import asyncio
import aio_etcd as etcd

async def watcher():
    client = etcd.Client()
    result = await client.watch('/nodes/n1')

def main():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(watcher())
    
if __name__ == '__main__':
    main()
```

It raises:

```python

Traceback (most recent call last):
  File "/Users/Dani/Documents/Projects/etcd_watcher/watcher.py", line 2, in <module>
    import aio_etcd as etcd
  File "/Users/Dani/.virtualenvs/aioetcd/lib/python3.5/site-packages/aio_etcd/__init__.py", line 3, in <module>
    from .client import Client
  File "/Users/Dani/.virtualenvs/aioetcd/lib/python3.5/site-packages/aio_etcd/client.py", line 12, in <module>
    from aiohttp.errors import DisconnectedError,ClientConnectionError,ClientResponseError
ImportError: No module named 'aiohttp.errors'

Process finished with exit code 1
```

I need to do:

```bash

> pip uninstall -y aiohttp
> pip install -y "aiohttp<2"
```

Then, I can run again the above code and only it's runs.

**Comment by smurfix** [comment]
Please re-test with the current version. I already uploaded a rather trivial change that fixes this import error.

**Comment by cr0hn** [comment]
After update the Pypi version, it runs! thx :)

**Pull request closed without merging**
